import React from 'react'
import styles from '../styles/Home.module.css'
const contact = () => {
  return (
    <div className={styles.content}>
     <Head>
        <title>Sarthak Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/webicon.png" />
      </Head>
          <h2>Contact Information</h2>
          <p>Phone no. 123456789</p>
          <p>Email- music@abc.com</p>
          <p>Address-123,Indore,M.P</p>
         </div>
  )
}

export default contact
